import '@/app/globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Header from './components/header';
import Footer from './components/footer';
import { NextJsLayout } from '@/app/types/pages';
import { languages } from '../i18n/config';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return languages.map((language) => ({ lng: language }));
}

export default async function RootLayout({
  children,
  about,
  experience,
  params: { lng },
}: NextJsLayout) {
  return (
    <html lang={lng}>
      <body className={inter.className}>
        <Header lng={lng} />
        <div>{children}</div>
        <div>{experience}</div>
        <div>{about}</div>
        <Footer />
      </body>
    </html>
  );
}
